[workspace]
resolver = "2"

members = [
    "neon/native",
]

[profile.release]
opt-level = "s"
overflow-checks = true

[patch.crates-io]
ledger-zcash-builder = { path = "../../ledger-zcash-rs/ledger-zcash-builder" }
ledger-zcash = { path = "../../ledger-zcash-rs/ledger-zcash" }
